Capitulating on the whole PEP-8 indent style.

diff --git a/examples/run b/examples/run
--- a/examples/run
+++ b/examples/run
@@ -23,94 +23,94 @@ PYTHON=python
 
 PYTHON_VERSION="$($PYTHON --version 2>&1)"
 if [ "$?" -ne 0 ]; then
-	echo $PYTHON_VERSION >&2
-	exit 1
+    echo $PYTHON_VERSION >&2
+    exit 1
 fi
 
 usage()
 {
-	cat >&2 <<EOT
+    cat >&2 <<EOT
 Usage: ./$P [-v] [-l] [-C] [-A] [-x] [-w addr] [-c certfile] role [...]
 
        Run the example configuration in the specified role.
        This must be run from within the example directory, ie:
 
-       		cd ..../taskforce/examples
-		./$P
+            cd ..../taskforce/examples
+        ./$P
 
        Log output will be to stderr.
 
        Flags:
-	-h	This message.
+    -h  This message.
 
-	-v	Enable verbose logging in the example run.
+    -v  Enable verbose logging in the example run.
 
-	-l	Log to syslog
+    -l  Log to syslog
 
-	-c	Override examples certificate file
+    -c  Override examples certificate file
 
-	-C	Check the config and exit
+    -C  Check the config and exit
 
-	-A	Allow HTTP operations that can change the
-		task state.
+    -A  Allow HTTP operations that can change the
+        task state.
 
-	-x	Cause simulated ntpd to exit randomly to
-		demonstrate the 'timeset' restart.
+    -x  Cause simulated ntpd to exit randomly to
+        demonstrate the 'timeset' restart.
 
-	-w	Listen for HTTP on addr
+    -w  Listen for HTTP on addr
 
 EOT
-	exit "${1:-99}"
+    exit "${1:-99}"
 }
 
 TFARGS=
 LOGDEST='--log-stderr'
 while [ "$#" -gt 0 ]; do
-	case "$1" in
-	-v*)
-		TFARGS="$TFARGS --verbose"
-		;;
-	-l*)
-		LOGDEST=''
-		;;
-	-C*)
-		TFARGS="$TFARGS --check-config"
-		;;
-	-A*)
-		TFARGS="$TFARGS --allow-control"
-		;;
-	-c*)
-		shift
-		TFARGS="$TFARGS --certfile $1"
-		;;
-	-w*)
-		shift
-		TFARGS="$TFARGS --http $1"
-		;;
-	-x*)	MINSLEEP=20; export MINSLEEP
-		SLEEPRANGE=20; export SLEEPRANGE
-		;;
-	-h)
-		usage 0
-		;;
-	--)
-		shift
-		break
-		;;
-	-*)
-		echo "$P: Unknown flag '$1'" >&2
-		usage
-		;;
-	*)
-		break
-		;;
-	esac
-	shift
+    case "$1" in
+    -v*)
+        TFARGS="$TFARGS --verbose"
+        ;;
+    -l*)
+        LOGDEST=''
+        ;;
+    -C*)
+        TFARGS="$TFARGS --check-config"
+        ;;
+    -A*)
+        TFARGS="$TFARGS --allow-control"
+        ;;
+    -c*)
+        shift
+        TFARGS="$TFARGS --certfile $1"
+        ;;
+    -w*)
+        shift
+        TFARGS="$TFARGS --http $1"
+        ;;
+    -x*)    MINSLEEP=20; export MINSLEEP
+        SLEEPRANGE=20; export SLEEPRANGE
+        ;;
+    -h)
+        usage 0
+        ;;
+    --)
+        shift
+        break
+        ;;
+    -*)
+        echo "$P: Unknown flag '$1'" >&2
+        usage
+        ;;
+    *)
+        break
+        ;;
+    esac
+    shift
 done
 
 if [ "$#" -eq 0 ]; then
-	echo "$P: At least one role needed" >&2
-	usage
+    echo "$P: At least one role needed" >&2
+    usage
 fi
 
 TFBASE="$(cd .. && echo $PWD)"
@@ -119,33 +119,33 @@ EXBIN="$EXAMPLES_BASE/bin"
 EXCONF="$EXAMPLES_BASE/example.conf"
 EXROLES="$EXAMPLES_BASE/example.roles"
 if [ ! -x "$EXBIN/procsim" ]; then
-	echo "$P: Script must be run from the 'taskforce/examples' directory" >&2
-	exit 2
+    echo "$P: Script must be run from the 'taskforce/examples' directory" >&2
+    exit 2
 fi
 if [ ! -r "$EXCONF" ]; then
-	echo "$P: Example config '$EXCONF' is missing" >&2
-	exit 2
+    echo "$P: Example config '$EXCONF' is missing" >&2
+    exit 2
 fi
 TFBIN="$TFBASE/bin"
 if [ ! -x "$TFBIN/taskforce" ]; then
-	echo "$P: 'taskforce' application not found in '$TFBIN'" >&2
-	exit 2
+    echo "$P: 'taskforce' application not found in '$TFBIN'" >&2
+    exit 2
 fi
 TFPKG="$TFBASE/taskforce"
 if [ ! -f "$TFPKG/__init__.py" ]; then
-	echo "$P: 'taskforce' package not found in '$TFPKG'" >&2
-	exit 2
+    echo "$P: 'taskforce' package not found in '$TFPKG'" >&2
+    exit 2
 fi
 if [ ! -d "$EXAMPLES_BASE/var/run" ]; then
-	mkdir -p "$EXAMPLES_BASE/var/run" || exit 3
+    mkdir -p "$EXAMPLES_BASE/var/run" || exit 3
 fi
 PATH=$EXBIN:$PATH; export PATH
 PYTHONPATH=$TFBASE:$PYTHONPATH; export PYTHONPATH
 
 > $EXROLES || exit 3
 while [ "$#" -gt 0 ]; do
-	echo $1 >> $EXROLES
-	shift
+    echo $1 >> $EXROLES
+    shift
 done
 
 exec $PYTHON $TFBIN/taskforce $LOGDEST $TFARGS --config-file $EXCONF --roles-file $EXROLES
